name: Cloudron Auto Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CLOUDRON_APP: ${{ secrets.CLOUDRON_APP }}  # ID de votre application Cloudron
      CLOUDRON_SERVER: ${{ secrets.CLOUDRON_SERVER }}  # URL de votre serveur Cloudron
      CLOUDRON_TOKEN: ${{ secrets.CLOUDRON_TOKEN }}  # Jeton d'authentification Cloudron
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}  # Nom de votre image Docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cloudron CLI
        run: npm install -g cloudron

      - name: Update App
        run: |
          update="cloudron update --no-wait \
            --server $CLOUDRON_SERVER \
            --token $CLOUDRON_TOKEN \
            --app $CLOUDRON_APP \
            --image $DOCKER_IMAGE"
          # Retry up to 5 times (with linear backoff)
          NEXT_WAIT_TIME=0
          until [ $NEXT_WAIT_TIME -eq 5 ] || $update; do
              sleep $(( NEXT_WAIT_TIME++ ))
          done
          [ $NEXT_WAIT_TIME -lt 5 ]
