name: Docker Image CI

on:
  push:
    branches:
      - main
      - dev  # Exécute le workflow sur la branche dev
  pull_request:
    branches:
      - main
      - dev  # Exécute le workflow sur les pull requests vers dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag python-fastapi:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Ajoute ton nom d'utilisateur Docker Hub dans les secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Ajoute ton mot de passe Docker Hub dans les secrets

      - name: Push Docker image
        run: |
          docker tag python-fastapi:latest ${{ secrets.DOCKER_USERNAME }}/python-fastapi:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/python-fastapi:latest
